# Generated by Django 4.2.4 on 2023-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thuthu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thu_thu', models.CharField(max_length=10, unique=True)),
                ('ten_thu_thu', models.CharField(max_length=50)),
                ('mat_khau', models.CharField(max_length=30)),
            ],
        ),
    ]
