# Generated by Django 4.2.3 on 2023-08-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang_nhap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuthu',
            name='ten_dang_nhap',
        ),
    ]
