# Generated by Django 4.2.4 on 2023-08-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang_nhap', '0003_docgia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocGia',
        ),
    ]
