# Generated by Django 4.2.4 on 2023-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sach', models.CharField(max_length=10, unique=True)),
                ('ten_sach', models.CharField(max_length=200)),
                ('ten_tac_gia', models.CharField(max_length=100)),
                ('nam_xuat_ban', models.PositiveIntegerField()),
                ('so_luong_con', models.PositiveIntegerField()),
                ('so_luong_muon', models.PositiveIntegerField(default=0)),
                ('loai_sach', models.CharField(choices=[('TRUYEN', 'Truyện'), ('KY_NANG', 'Kỹ năng'), ('KIEN_THUC', 'Kiến thức'), ('VAN_HOC', 'Văn học'), ('KHOA_HOC', 'Khoa học'), ('KHAC', 'Khác')], max_length=10)),
            ],
        ),
    ]
