# Generated by Django 4.2.4 on 2023-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sach', models.CharField(max_length=10, unique=True)),
                ('ten_sach', models.CharField(max_length=100)),
                ('tac_gia', models.CharField(max_length=100)),
                ('nam_xuat_ban', models.IntegerField()),
                ('so_luong', models.IntegerField()),
                ('loai_sach', models.CharField(max_length=50)),
            ],
        ),
    ]
