# Generated by Django 4.2.3 on 2023-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_sach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sach',
            old_name='so_luong',
            new_name='so_luong_con',
        ),
        migrations.AddField(
            model_name='sach',
            name='so_luong_muon',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
