# Generated by Django 4.2.4 on 2023-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_sach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='so_luong',
        ),
        migrations.AddField(
            model_name='sach',
            name='so_luong_con',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sach',
            name='so_luong_muon',
            field=models.IntegerField(default=0),
        ),
    ]
