# Generated by Django 4.2.4 on 2023-08-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dang_nhap', '0002_remove_thuthu_ten_dang_nhap'),
        ('quan_ly_doc_gia', '0001_initial'),
        ('quan_ly_sach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuonTraSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('ngay_muon', models.DateField()),
                ('ngay_hen_tra', models.DateField()),
                ('ngay_tra', models.DateField(blank=True, null=True)),
                ('ma_doc_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_doc_gia.docgia')),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quan_ly_sach.sach')),
                ('ma_thu_thu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang_nhap.thuthu')),
            ],
            options={
                'unique_together': {('ma_thu_thu', 'ma_doc_gia', 'ma_sach', 'ngay_muon')},
            },
        ),
    ]
