# Generated by Django 4.2.4 on 2023-08-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_muon_tra_sach', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='muontrasach',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='muontrasach',
            name='ma_doc_gia',
        ),
        migrations.RemoveField(
            model_name='muontrasach',
            name='ma_sach',
        ),
        migrations.RemoveField(
            model_name='muontrasach',
            name='ma_thu_thu',
        ),
    ]
