# Generated by Django 4.2.4 on 2023-08-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_muon_tra_sach', '0002_alter_muontrasach_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuonTraSach',
        ),
    ]
