# Generated by Django 4.2.4 on 2023-08-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quan_ly_muon_tra_sach', '0003_delete_muontrasach'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuonTraSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('ngay_muon', models.DateField()),
                ('ngay_hen_tra', models.DateField()),
                ('ngay_tra', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
