# Generated by Django 4.2.4 on 2023-08-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_doc_gia', '0003_initial'),
        ('dang_nhap', '0004_delete_docgia'),
        ('quan_ly_sach', '0001_initial'),
        ('quan_ly_muon_tra_sach', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muontrasach',
            name='ma_doc_gia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_doc_gia.docgia'),
        ),
        migrations.AddField(
            model_name='muontrasach',
            name='ma_sach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_sach.sach'),
        ),
        migrations.AddField(
            model_name='muontrasach',
            name='ma_thu_thu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dang_nhap.thuthu'),
        ),
    ]
