# Generated by Django 4.2.4 on 2023-08-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_doc_gia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocGia',
        ),
    ]
